#### 1. Write a function so that the columns of the output matrix are powers of the input vector.

#### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [8]:
import numpy as np

## Iterate over each number in the input vector n times, n being the number of columns in the o/p matrix and output 
## an intermediate vector. Use diff order formula based on increasing and decreasing condition.
## Reshape the intermediate vector using the size of the input vector (rows) and n (columns) to generate the o/p matrix. 
   
def generate_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        output_matrix = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        output_matrix = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return output_matrix

In [9]:
#lets declare input array and no. of columns in output matrix
input_vector=np.array([1,2,3,4,5])
num_of_columns=3
#print the output matrix in decreasing order
output_matrix_dec_order = generate_vander_matrix(input_vector,num_of_columns,False)
#print the output matrix in increasing order
output_matrix_inc_order = generate_vander_matrix(input_vector,num_of_columns,True)
#print output
print('OUTPUT:')
print("The input array is:",input_vector,"\n")
print("Number of columns in output matrix should be:",num_of_columns,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",output_matrix_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",output_matrix_inc_order,"\n")

OUTPUT:
The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 



#### 2.Problem Statement
#### Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
#### the given sequence is defined as follows:
#### The moving average sequence has n-k+1 elements as shown below.
#### The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values
#### Question: Write a function to find moving average in an array over a window:
#### Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [10]:
import numpy as np
def moving_average(a, n=3) :
# we use np.cumsum to get a cumulative sum of the numbers
 asum = np.cumsum(a, dtype=float)
#We are breaking the array as per desired number which is 'n' in our function
#and subtracting elements to get the desired result
 asum[n:] = asum[n:] - asum[:-n]
 return asum[n - 1:] / n
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
a1=np.array(a)
#rounding off the results to two digts
np.array(moving_average(a1,n=3)).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])